name: "test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci-ci.yaml ./...
      - name: Test
        run: |
          go test ./...

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci-ci.yaml
      - name: Test
        run: |
          go test ./... -race
